### ISSUE TITLE
inclusion of updated oracle source version to match with solc compiler declared in the project

### ISSUE THREAD

**Issue by gledsoul** [block-foundation/solidity-smart-home#1]
### Sample

https://infrablok.com/tutorial-to-connect-apis-from-ethereum-smart-contracts-using-chainlink-oracles/

### Author(s)

@gledsoul

### Suggestion

import "@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol";

Actually the project is not compiling due to out of date version declared on the Contract.

### Are you willing to help?

Yes

**Comment by vanvianen** [comment]
Thanks @gledsoul !
Very much appreciated!
