### ISSUE TITLE
execute  npm install @chainlink/contracts --save or include this it on package.json

### ISSUE THREAD

**Issue by gledsoul** [block-foundation/solidity-smart-home#2]
### Sample

npm install @chainlink/contracts --save

### Author(s)

gledsoul

### What happened?

npm install @chainlink/contracts --save

### Steps to reproduce

1.
2.
3.
npm install @chainlink/contracts --save

### Expected behavior

npm install @chainlink/contracts --save

**Comment by vanvianen** [comment]
Addressed both your issues in the last commits:)
This repo is still very much a WIP > your help is indeed invaluable! 
Many thanks
